### ISSUE TITLE
Decoration is Missing

### ISSUE THREAD

**Issue by AbdurahmanAb** [indratrisnar/d_input#1]
There is no Option for using Input decoration  with out decoration it can not be customized as we want . It should accept Input Decoration like border border color focus color ....

**Comment by indratrisnar** [comment]
d_input is package for simple style with default border input and concise
code. If you want full custom style, you can use TextField or TextFormField

Pada Min, 14 Jan 2024 01.46, Abdu A ***@***.***> menulis:
